# Generated by Django 4.2.1 on 2023-06-26 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0003_project_ideas_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_Ideas',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='course',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
