# Generated by Django 4.2.1 on 2023-06-26 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0005_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.IntegerField(choices=[(0, 'mini project'), (1, 'main project'), (2, 'live project')])),
                ('Description', models.TextField()),
                ('project_title', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.course')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('technology', models.ManyToManyField(blank=True, to='ideas.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
